---

- name: enable epel
  yum: name=epel-release state=present

- name: install pkg
  yum: name={{ item }} state=installed
  with_items:
   - redis
  notify:
   - svc restart redis

- name: service enable, start
  service: name=redis state=started enabled=yes

