---

- name: enable epel
  yum: name=epel-release state=present
  when: ansible_distribution == "CentOS"

- name: install pkg
  yum: name={{ item }} state=installed
  with_items:
   - redis
  notify:
   - svc restart redis

- name: cfg
  lineinfile:
    regexp: '^{{ item }}'
    dest: '{{ redis_conf }}'
    state: 'absent'
  with_items:
    - 'bind'

- name: service enable, start
  service: name=redis state=started enabled=yes

